services:
  web:
    build: .
    volumes:
      - .:/app
  web_migrate:
    extends:
      service: web
    command: python manage.py migrate && python manage.py loaddata muteAudio.json
  web_run:
    extends:
      service: web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"