services:
  web:
    build: .
    volumes:
      - sqlite-db:/app/sb.sqlite3
  web_run:
    extends:
      service: web
    command: python manage.py runserver --settings web_project.settings.prod 0.0.0.0:8000
    ports:
      - "8000:8000"

volumes:
  sqlite-db: