services:
  web:
    build: .
    volumes:
      - .:/app
  web_run:
    extends:
      service: web
    command: python manage.py runserver --settings web_project.settings.dev 0.0.0.0:8000
    ports:
      - "8000:8000"